### ISSUE TITLE
Access-Control-Allow-Headers is too strict for Safari with DNT enabled

### ISSUE THREAD

**Issue by iwehrman** [jspm/jspm.io#18]
![DNT](https://s3.amazonaws.com/f.cl.ly/items/2O1S0h3d1F102V1B2r1n/Image%202015-01-07%20at%208.15.39%20AM.png)

**Comment by guybedford** [comment]
Thanks, I've added `dnt` as an allowed header - let me know if that works ok now?

**Comment by iwehrman** [comment]
:+1: Thanks!
