### ISSUE TITLE
Server returns 301 instead of 404

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm.io#22]
Attempting to use the CDN approach to loading System.js et al and stumbled onto a problem where it seems to be generating the wrong URL for one of the files it is trying to load (traceur-runtime in this particular case). In trying to debug this things were complicated by my browser giving an obtuse CORS related error instead of a simple 404 Not Found. It seems that requests to invalid addresses at `https://jspm.io/*` currently get 301 redirected to `http://jspm.io`. The fact that there is a redirect here and that the redirect hops from HTTPS to HTTP causes the CORS issue I was seeing. It would have saved me several minutes of confusion if, particularly for CDN or CDN-like paths, the server would respond with a proper 404 instead of a confusing 301.

Hopefully this is the right repository to post this issue to. (Now I will likely try to figure out why traceur-runtime is trying to use the wrong address and/or include it in my bundle...)

**Comment by guybedford** [comment]
Thanks for posting. There was actually a typo where the latest traceur-runtime was saved as `traceur-runtim@0.0.82.js` instead of `traceur-runtime@0.0.82.js`. I've fixed this now and it should be working.

Good point about the 301, I've altered it to do a 404 when there's a path, which make much more sense as you say.

**Comment by WorldMaker** [comment]
Excellent. Thanks for the 404s. In the case of my little demo app it's trying to pull `traceur@0.0.82-runtime.js`. Seems strange that the version migrated to the middle of the name like that.

**Comment by guybedford** [comment]
Ok yes that is a bug in the loader working out the name for Traceur runtime. There will be some updates to this in the next release. For now you can at least include `<script src="https://jspm.io/traceur-runtime.js">` manually.

**Comment by WorldMaker** [comment]
:ok_hand:
