### ISSUE TITLE
Missing "Vary:Accept-Encoding"

### ISSUE THREAD

**Issue by lilred** [jspm/jspm.io#25]
The problem:
When using <script> tags to include a file hosted on jspm.io, it comes back as mangled. I can still access it if I just enter the URL in my address bar, though.

How it came up:
This isn't a problem that affects production websites, but jspm-hosted .js files can be used in demos such as [the Angular2 quick start tutorial](https://angular.io/docs/js/latest/quickstart.html).

The explanation + solution:
https://www.maxcdn.com/blog/accept-encoding-its-vary-important/

**Comment by lilred** [comment]
Reopened at jspm/registry.

**Comment by guybedford** [comment]
This is the right place for it, thanks.
