### ISSUE TITLE
Infinite spinner on https://jspm.io

### ISSUE THREAD

**Issue by ffffranklin** [jspm/jspm.io#26]
**Steps to reproduce**
1. Navigate to https://jspm.io
2. Observe the loading indicator displays but content never renders

**Actual Result**
See Infinite spinner
![screen shot 2015-06-18 at 4 47 55 pm](https://cloud.githubusercontent.com/assets/1546561/8244794/43abf774-15da-11e5-9ad8-c0a2d59beaa1.png)

**Expected Result**
Should see content
![screen shot 2013-07-25 at 23 38 00](https://cloud.githubusercontent.com/assets/1546561/8244809/7be02110-15da-11e5-90e8-20316aae418f.png)

**Notes**
showdown.js seems to hang:
![screen shot 2015-06-18 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/1546561/8245173/64aa3382-15df-11e5-8ee8-042946517e5c.png)

**OS:** OSX 10.10.3
**Browser:** Chrome Version 43.0.2357.124 (64-bit)

**Comment by guybedford** [comment]
Thanks, yes the GitHub lookups have been failing a bit recently sporadically, so need to introduce better resilience of handling these failures on the server.

For now I've just had to implement better monitoring, but hope to look into it properly soon.

**Comment by ffffranklin** [comment]
Ah, would be nice if there was a timeout config value for jspm or es6-module-loader.   FYI I can't seem to reproduce this issue so perhaps this can be closed.

**Comment by ffffranklin** [comment]
nm I can still reproduce

![screenshot](https://cloud.githubusercontent.com/assets/1546561/8265942/b0f1c908-16c5-11e5-9123-7262c0491578.png)

**Comment by xak2000** [comment]
Seems like http server problem.
`jspm.io` shows spinner.
Trying to open `https://jspm.io/system@0.16.js` shows `ERR_CONNECTION_REFUSED`.

**Comment by douglasduteil** [comment]
Wow all the remote services are down bro !
- https://npm.jspm.io/
- https://github.jspm.io/

**Comment by guybedford** [comment]
Thanks, was out of internet. Very difficult to be on pager duty as one person :)

**Comment by VladimirKorablev** [comment]
hi!
still down
GET https://jspm.io/system@0.16.js net::ERR_CONNECTION_REFUSED

**Comment by guybedford** [comment]
Thanks, back up. This server stuff is hard work... Anyone feel like helping me with this!?

**Comment by guybedford** [comment]
I believe I've managed to find the root cause of the cascade issue on some cluster failures, hopefully we should get back up to decent uptime again soon.

**Comment by xak2000** [comment]
Big thank you! :)

**Comment by JohannesHoppe** [comment]
The [Angular 5 Quickstart](https://angular.io/docs/js/latest/quickstart.html) uses the experimental CDN. This might be a big source of new users already using it. 
This afternoon github.jspm.io or jspm.io was down ( i don't remember). I'm wondering what type of server is behind the CDN? Do you already use a service like cloudflare.com in front of your servers?

**Comment by stefanlange** [comment]
Down again ...

**Comment by guybedford** [comment]
Thanks, it's back up and I've attempted a fix.

**Comment by JohannesHoppe** [comment]
Trying to load https://npm.jspm.io/angular2@2.0.0-alpha.44/angular2.js - endless waiting, white page, then a 500.
https://npm.jspm.io/ seems to have a bad day again?!

**Comment by JohannesHoppe** [comment]
I might have found an issue.

As mentioned in https://github.com/jspm/registry/pull/596 , you are having issues with the slash in the name of rxjs. That might be an explanation.

GET https://npm.jspm.io/@reactivex/rxjs@5.0.0-alpha.7.js
---> error 500

After that your server seems to be super-busy:
GET https://npm.jspm.io/angular2@2.0.0-alpha.44/angular2.js
---> endless loading

After a (very long) waiting time the server can deliver again "angular2.js". As soon as i trigger the error 500, the server is busy again.

**Comment by alisd23** [comment]
Down again, same error as other people have mentioned
`GET https://jspm.io/system@0.19.js net::ERR_TIMED_OUT`
