### ISSUE TITLE
Is this a bug

### ISSUE THREAD

**Issue by hon** [jspm/jspm.io#30]
I import a custom module like this:
```javascript
import MaintenanceActions from '../../flux/stores/MaintenanceStore';
```
but failed with this error:
```
GET http://localhost:9000/jspm_packages/npm/flux@2.0.3/stores/MaintenanceStore.js 404 (Not Found)
```
It seems that the loader parse the 'flux' to the flux  module.
Is this a bug or I made some mistakes?

**Comment by guybedford** [comment]
Yes this looks like a bug. Which version of jspm are you running? Try upgrading to the beta if you're not already using it and see if that helps here?
