### ISSUE TITLE
JSPM behind Corporate Proxy

### ISSUE THREAD

**Issue by siddharthjain210** [jspm/jspm.io#32]
JSPM fails to work if we are running it behind corporate proxy. I have set up HTTP_PROXY as well as HTTPS_PROXY. It gives me the following error whenever i try to install any component.

Error on locate for github:components/COMPONENT_NAME
Error: unable to verify the first certificate

I couldn't find any documentation how to configure proxy for JSPM on windows. Please help.

**Comment by guybedford** [comment]
Have you tried editing your `~/.jspm/config` file and adding a base-level "strictSSL: false" property here?

**Comment by siddharthjain210** [comment]
@guybedford :Yes i have tried adding a base-Level property for strictssl too.
This is the error i am getiing when i run 
jspm install jquery:
****************************************************************
     Updating registry cache...
     Looking up github:components/jquery
     Downloading github:components/jquery@2.1.4

err  Error: incorrect header check
         at Zlib._handle.onerror (zlib.js:366:17)
*******************************************************************

**Comment by guybedford** [comment]
@siddharthjain210 I think your issue here would be resolved by permitting custom certificates as in https://github.com/jspm/jspm-cli/issues/980. Let's track there.
