### ISSUE TITLE
Bundle dynamic imports

### ISSUE THREAD

**Issue by redmagic** [jspm/jspm.io#34]
Hi,

I am using System.import to dynamically load dependencies. For example to only run certain scripts when certain elements are on the page.

jspm bundle cannot resolve these imports (naturally).

Is there any wayI can tell jspm to create a self executing bundle and feed it additional modules that need to be included although they are not present as import statements?

Thanks,

Arjen

**Comment by guybedford** [comment]
This would be a nice feature and is being tracked in https://github.com/systemjs/builder/issues/75, but is currently not being prioritised. A regular expression in a custom build step may well work for you here in the mean time.
