### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by kijanawoodard** [jspm/jspm.io#35]
Is jspm supposed to work on Edge?

I noticed http://jspm.io/ doesn't work.

**Comment by guybedford** [comment]
Thanks for posting here! I believe I have fixed the bug now, but let me know if you notice any further issues at all.

**Comment by kijanawoodard** [comment]
For no particular reason, I tried this again today. It appears to be broken again.

While http://jspm.io/ works in chrome, there's a 404 for showdown@1.2.2 in Edge.
Interestingly, showdown@1.2.2,js gets a 301 from registry.jspm.io to github.jspm.io in Chrome.

**Comment by guybedford** [comment]
@kijanawoodard thanks for the follow up. That might have been due to some instability on the jspm server at the time - as there was a hack attempt last week (due to a range attack not targeting). I just tried it out now and it seems fine to me.
