### ISSUE TITLE
http://jspm.io/ not loading content

### ISSUE THREAD

**Issue by ricog** [jspm/jspm.io#40]
The screen is blank and the browser is loading for approximately 30 seconds until the page renders with the spinner, but no content.

What I see:
![](https://dl.dropboxusercontent.com/s/llyaqjd1n55985t/2016-01-28%20at%2010.25%20AM.png?dl=0)

What I expect:
That page, but with content below the logo and tag line instead of the spinner icon.

Steps to reproduce:

Go to http://jspm.io/ in your browser

**Comment by guybedford** [comment]
Thanks, it's back up now.
