### ISSUE TITLE
SPDY no longer supported in Chrome 50

### ISSUE THREAD

**Issue by probins** [jspm/jspm.io#44]
Not sure where to raise this issue, but as module delivery is on jspm.io ...

https://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html
https://www.chromestatus.com/features/5711167683035136

**Comment by guybedford** [comment]
Thanks for the reminder here! I've done the upgrade now.

**Comment by probins** [comment]
just checked on this. Chrome has a nifty extension that displays whether a site is using SPDY/HTTP2/neither, and with for example https://github.jspm.io/probins/map-make@master/mapDef.js it tells me it's still using SPDY 3.1 - or is this some caching issue?

**Comment by guybedford** [comment]
It's definitely showing up as "h2" for me in the chrome://net-internals HTTP/2 tab.

**Comment by probins** [comment]
yes, for me too. So I loaded jspm.io and tried the System.import(Buffer) example. The Chrome extension shows h2 for https://npm.jspm.io/buffer@3.0.js, so the example I gave before is probably using a cached version, which will disappear over time.

Thanks a lot 👏

**Comment by guybedford** [comment]
Sure, appreciated for checking!

**Comment by probins** [comment]
fyi, turns out Google was providing some false info: SPDY is being removed in Chrome 51 not 50, so another month or so till it's in the stable version https://bugs.chromium.org/p/chromium/issues/detail?id=587469#c5 - never mind, server needed updating anyway :-)
