### ISSUE TITLE
Edit docs button

### ISSUE THREAD

**Issue by peteruithoven** [jspm/jspm.io#45]
I was hoping to clarify some things  the [0.17@beta Linking docs](http://jspm.io/0.17-beta-guide/linking.html), but I'm not sure how... The docs in this repo seem to be plain html, which might be a endresult of a compilation step. 
Redux, which also uses GitBook, added a Edit link ("Edit this page") to their docs which makes this easier. It looks like they use an `edit-link` plugin for that. Their whole book config:
https://github.com/reactjs/redux/blob/master/book.json
Wouldn't this be interesting for the JSPM's docs?

**Comment by guybedford** [comment]
That would definitely be useful to encourage editing! The beta documentation is currently at https://github.com/guybedford/jspm-beta-guide.
