### ISSUE TITLE
jspm.browser.js not created with default init settings

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm.io#47]
Hey,

The documentation implies that a file `jspm.browser.js` will be created when I run `jspm init .` I think this might've been true previously, but it is not true with `0.17.0-beta.22`

When I select `Custom` instead of `Quick` I see the option to have this file created.

I don't have a strong preference on whether this file should exist or not, but the documentation should align with the defaults. Thanks.

**Comment by guybedford** [comment]
Yes as of the latest beta, the browser configuration is not created by default. When running `jspm init`, with standard / custom settings you can choose to bring this back, or simply create an empty `jspm.browser.js` and run `jspm clean` to get it to apply.
