### ISSUE TITLE
Is there a typo in plugins section, on how to import json files?

### ISSUE THREAD

**Issue by einaradolfsen** [jspm/jspm.io#58]
In the git book it says in section 5. plugins:
import config from './config-service!json';  // ---> errors when using exclamation mark in front of json

I tried to import json file in the same manor as described for css files

import config from './config-service.json!'; // ---> imports the json

**Comment by guybedford** [comment]
You need to make sure you have the JSON plugin configured for this case - https://github.com/systemjs/plugin-json.
